# generate CICD for my cloud
name: CICDEXPRESS

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: pavitpim40/node-ci:latest

            - name: Deploy to Cloud
              uses: appleboy/ssh-action@master
              with:
                  host: 139.5.147.220
                  username: nc-user
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
